### ISSUE TITLE
sort out how to deal with databroker building

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/auto-build-tagged-recipes#2]
```
BUILD START: databroker-0.3.0-py34_0
Fetching package metadata: ........
Solving package specifications: .............Cloning into '/tmp/edill/ramdisk/mc/conda-bld/work'...
done.
Note: checking out 'v0.3.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at cf2a1fc... Tag v0.3.0
+ /tmp/edill/ramdisk/mc/envs/_build/bin/python setup.py install
running install
running bdist_egg
running egg_info
creating databroker.egg-info
writing top-level names to databroker.egg-info/top_level.txt
writing databroker.egg-info/PKG-INFO
writing dependency_links to databroker.egg-info/dependency_links.txt
writing manifest file 'databroker.egg-info/SOURCES.txt'
reading manifest file 'databroker.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'databroker.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/databroker
copying databroker/_version.py -> build/lib/databroker
copying databroker/databroker.py -> build/lib/databroker
copying databroker/__init__.py -> build/lib/databroker
copying databroker/pims_readers.py -> build/lib/databroker
copying databroker/handler_registration.py -> build/lib/databroker
creating build/lib/databroker/testing
copying databroker/testing/decorators.py -> build/lib/databroker/testing
copying databroker/testing/utils.py -> build/lib/databroker/testing
copying databroker/testing/__init__.py -> build/lib/databroker/testing
copying databroker/testing/noseclasses.py -> build/lib/databroker/testing
creating build/lib/databroker/examples
copying databroker/examples/hdf_io.py -> build/lib/databroker/examples
copying databroker/examples/__init__.py -> build/lib/databroker/examples
creating build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/step_scan.py -> build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/common_nonscalar.py -> build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/__init__.py -> build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/image_and_scalar.py -> build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/frame_generators.py -> build/lib/databroker/examples/sample_data
creating build/lib/databroker/utils
copying databroker/utils/diagnostics.py -> build/lib/databroker/utils
copying databroker/utils/__init__.py -> build/lib/databroker/utils
UPDATING build/lib/databroker/_version.py
set build/lib/databroker/_version.py to '0.3.0'
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/databroker
creating build/bdist.linux-x86_64/egg/databroker/utils
copying build/lib/databroker/utils/diagnostics.py -> build/bdist.linux-x86_64/egg/databroker/utils
copying build/lib/databroker/utils/__init__.py -> build/bdist.linux-x86_64/egg/databroker/utils
creating build/bdist.linux-x86_64/egg/databroker/testing
copying build/lib/databroker/testing/decorators.py -> build/bdist.linux-x86_64/egg/databroker/testing
copying build/lib/databroker/testing/utils.py -> build/bdist.linux-x86_64/egg/databroker/testing
copying build/lib/databroker/testing/__init__.py -> build/bdist.linux-x86_64/egg/databroker/testing
copying build/lib/databroker/testing/noseclasses.py -> build/bdist.linux-x86_64/egg/databroker/testing
copying build/lib/databroker/_version.py -> build/bdist.linux-x86_64/egg/databroker
copying build/lib/databroker/databroker.py -> build/bdist.linux-x86_64/egg/databroker
copying build/lib/databroker/__init__.py -> build/bdist.linux-x86_64/egg/databroker
creating build/bdist.linux-x86_64/egg/databroker/examples
copying build/lib/databroker/examples/hdf_io.py -> build/bdist.linux-x86_64/egg/databroker/examples
copying build/lib/databroker/examples/__init__.py -> build/bdist.linux-x86_64/egg/databroker/examples
creating build/bdist.linux-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/step_scan.py -> build/bdist.linux-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/common_nonscalar.py -> build/bdist.linux-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/__init__.py -> build/bdist.linux-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/image_and_scalar.py -> build/bdist.linux-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/frame_generators.py -> build/bdist.linux-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/pims_readers.py -> build/bdist.linux-x86_64/egg/databroker
copying build/lib/databroker/handler_registration.py -> build/bdist.linux-x86_64/egg/databroker
byte-compiling build/bdist.linux-x86_64/egg/databroker/utils/diagnostics.py to diagnostics.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/utils/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/testing/decorators.py to decorators.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/testing/utils.py to utils.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/testing/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/testing/noseclasses.py to noseclasses.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/_version.py to _version.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/databroker.py to databroker.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/examples/hdf_io.py to hdf_io.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/examples/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/examples/sample_data/step_scan.py to step_scan.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/examples/sample_data/common_nonscalar.py to common_nonscalar.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/examples/sample_data/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/examples/sample_data/image_and_scalar.py to image_and_scalar.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/examples/sample_data/frame_generators.py to frame_generators.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/pims_readers.py to pims_readers.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/databroker/handler_registration.py to handler_registration.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying databroker.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying databroker.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying databroker.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying databroker.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/databroker-0.3.0-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing databroker-0.3.0-py3.4.egg
Copying databroker-0.3.0-py3.4.egg to /tmp/edill/ramdisk/mc/envs/_build/lib/python3.4/site-packages
Adding databroker 0.3.0 to easy-install.pth file

Installed /tmp/edill/ramdisk/mc/envs/_build/lib/python3.4/site-packages/databroker-0.3.0-py3.4.egg
Processing dependencies for databroker==0.3.0
Finished processing dependencies for databroker==0.3.0
commit cf2a1fc0bf6ff6697ddb878424d4e52be879c212
Author: Eric Dill <edill@bnl.gov>
Date:   Tue Sep 29 09:51:04 2015 -0400

    Tag v0.3.0


v0.3.0


# Not currently on any branch.
nothing to commit (working directory clean)



The following NEW packages will be INSTALLED:

    ncurses:    5.9-7         https://pergamon.cs.nsls2.local:8443/conda/nsls2-tag/linux-64/
    openssl:    1.0.2d-0      https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    pip:        7.1.2-py34_0  https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    python:     3.4.4-0       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    readline:   6.2.5-1       file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    setuptools: 19.1.1-py34_0 https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    sqlite:     3.8.4.1-1     https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    tk:         8.5.18-0      https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    wheel:      0.26.0-py34_1 https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    xz:         5.0.5-0       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    zlib:       1.2.8-0       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 

Removing old work directory
checkout: 'v0.3.0'
==> git log -n1 <==

==> git describe --tags --dirty <==

==> git status <==

Package: databroker-0.3.0-py34_0
source tree in: /tmp/edill/ramdisk/mc/conda-bld/work
found egg: /tmp/edill/ramdisk/mc/envs/_build/lib/python3.4/site-packages/databroker-0.3.0-py3.4.egg
number of files: 2
Fixing permissions
Fixing permissions
BUILD END: databroker-0.3.0-py34_0
TEST START: databroker-0.3.0-py34_0
Fetching package metadata: ........
Solving package specifications: ........................................===== testing package: databroker-0.3.0-py34_0 =====
import: 'databroker'
Traceback (most recent call last):
  File "/tmp/edill/ramdisk/mc/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import databroker
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/edill/ramdisk/mc/envs/_test/lib/python3.4/site-packages/databroker-0.3.0-py3.4.egg/databroker/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/edill/ramdisk/mc/envs/_test/lib/python3.4/site-packages/databroker-0.3.0-py3.4.egg/databroker/databroker.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/edill/ramdisk/mc/envs/_test/lib/python3.4/site-packages/metadatastore-0.3.0+6.g7f89195-py3.4.egg/metadatastore/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/edill/ramdisk/mc/envs/_test/lib/python3.4/site-packages/metadatastore-0.3.0+6.g7f89195-py3.4.egg/metadatastore/conf.py", line 74, in <module>
  File "/tmp/edill/ramdisk/mc/envs/_test/lib/python3.4/site-packages/metadatastore-0.3.0+6.g7f89195-py3.4.egg/metadatastore/conf.py", line 70, in load_configuration
KeyError: "The configuration field(s) ['host', 'timezone', 'database', 'port'] were not found in any file or environmental variable."
/tmp/edill/ramdisk/mc/lib/python3.5/site-packages/requests/packages/urllib3/connection.py:266: SubjectAltNameWarning: Certificate for pergamon.cs.nsls2.local has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
/tmp/edill/ramdisk/mc/lib/python3.5/site-packages/requests/packages/urllib3/connection.py:266: SubjectAltNameWarning: Certificate for pergamon.cs.nsls2.local has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
/tmp/edill/ramdisk/mc/lib/python3.5/site-packages/requests/packages/urllib3/connection.py:266: SubjectAltNameWarning: Certificate for pergamon.cs.nsls2.local has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
/tmp/edill/ramdisk/mc/lib/python3.5/site-packages/requests/packages/urllib3/connection.py:266: SubjectAltNameWarning: Certificate for pergamon.cs.nsls2.local has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning

WARNING: conda-build appears to be out of date. You have version 1.19.0 but the
latest version is 1.19.0.post13. Run

conda update -n root conda-build

to get the latest version.

/tmp/edill/ramdisk/mc/lib/python3.5/site-packages/requests/packages/urllib3/connection.py:266: SubjectAltNameWarning: Certificate for pergamon.cs.nsls2.local has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning

WARNING: conda-build appears to be out of date. You have version 1.19.0 but the
latest version is 1.19.0.post13. Run

conda update -n root conda-build

to get the latest version.


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    metadatastore-0.3.0.post6  |           py34_0          62 KB  https://pergamon.cs.nsls2.local:8443/conda/nsls2/linux-64/
    databroker-0.3.0           |           py34_0          39 KB  file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/
    ------------------------------------------------------------
                                           Total:         101 KB

The following NEW packages will be INSTALLED:

    boltons:                  16.0.0.post8-8_g6d186bf_py34  file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    channelarchiver:          0.0.5.6-py34_1                file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    cycler:                   0.9.0-py34_0                  https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    databroker:               0.3.0-py34_0                  file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    doct:                     1.0.1-py34_0                  file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    filestore:                0.2.2.post5-5_g3bc4a5f_py34   https://pergamon.cs.nsls2.local:8443/conda/nsls2/linux-64/    
    fontconfig:               2.11.1-5                      https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    freetype:                 2.5.5-0                       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    h5py:                     2.5.0-np110py34_4             https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    hdf5:                     1.8.15.1-2                    https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    humanize:                 0.5.1-py34_0                  file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    jbig:                     2.1-0                         https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    jinja2:                   2.8-py34_0                    https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    jpeg:                     8d-0                          https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    jsonschema:               2.4.0-py34_0                  https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    libgfortran:              1.0-0                         https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    libpng:                   1.6.17-0                      https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    libtiff:                  4.0.6-1                       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    libxml2:                  2.9.2-0                       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    markupsafe:               0.23-py34_0                   https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    matplotlib:               1.5.1-np110py34_0             https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    metadatastore:            0.3.0.post6-py34_0            https://pergamon.cs.nsls2.local:8443/conda/nsls2/linux-64/    
    mongoengine:              0.10.5-py34_2                 file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    ncurses:                  5.9-7                         https://pergamon.cs.nsls2.local:8443/conda/nsls2-tag/linux-64/
    nslsii_dev_configuration: 2-3                           https://pergamon.cs.nsls2.local:8443/conda/nsls2-tag/linux-64/
    numpy:                    1.10.2-py34_0                 https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    openblas:                 0.2.14-3                      https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    openssl:                  1.0.2d-0                      https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    pandas:                   0.17.1-np110py34_0            https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    pillow:                   3.0.0-py34_1                  https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    pims:                     0.3.2.post30-30_g717a2de_py34 https://pergamon.cs.nsls2.local:8443/conda/nsls2/linux-64/    
    pip:                      7.1.2-py34_0                  https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    prettytable:              0.7.2-py34_0                  file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    pymongo:                  3.2.1.post0-0_g22fd629_py34   file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    pyparsing:                2.0.3-py34_0                  https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    pyqt:                     4.11.4-py34_1                 https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    python:                   3.4.4-0                       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    python-dateutil:          2.4.2-py34_0                  https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    pytz:                     2015.7-py34_0                 https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    pyyaml:                   3.11-py34_1                   https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    qt:                       4.8.7-1                       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    readline:                 6.2.5-1                       file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    scipy:                    0.16.1-np110py34_0            https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    setuptools:               19.1.1-py34_0                 https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    sip:                      4.16.9-py34_0                 https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    six:                      1.10.0-py34_0                 https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    slicerator:               0.9.7-py34_0                  file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    sqlite:                   3.8.4.1-1                     https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    tifffile:                 0.7.0-np110py34_1             file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    tk:                       8.5.18-0                      https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    tzlocal:                  1.1.2-py34_1                  file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    wheel:                    0.26.0-py34_1                 https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    xz:                       5.0.5-0                       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    yaml:                     0.1.6-0                       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    zlib:                     1.2.8-0                       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 

TESTS FAILED: databroker-0.3.0-py34_0

```

**Comment by tacaswell** [comment]
Aren't you just missing `nsls2_dev_configuration`?

**Comment by ericdill** [comment]
Thanks for the second set of eyes on this. As far as i can tell, that is being installed since the test section lists nslsii_dev_configuration in its `The following NEW packages will be INSTALLED` section.

**Comment by tacaswell** [comment]
I was looking at this section of the log

```
The following NEW packages will be INSTALLED:

    ncurses:    5.9-7         https://pergamon.cs.nsls2.local:8443/conda/nsls2-tag/linux-64/
    openssl:    1.0.2d-0      https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    pip:        7.1.2-py34_0  https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    python:     3.4.4-0       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    readline:   6.2.5-1       file:///tmp/edill/ramdisk/mc/conda-bld/linux-64/              
    setuptools: 19.1.1-py34_0 https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    sqlite:     3.8.4.1-1     https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    tk:         8.5.18-0      https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    wheel:      0.26.0-py34_1 https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    xz:         5.0.5-0       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 
    zlib:       1.2.8-0       https://pergamon.cs.nsls2.local:8443/conda/anaconda/linux-64/ 

Removing old work directory
checkout: 'v0.3.0'
==> git log -n1 <==

==> git describe --tags --dirty <==

==> git status <==

Package: databroker-0.3.0-py34_0
source tree in: /tmp/edill/ramdisk/mc/conda-bld/work
found egg: /tmp/edill/ramdisk/mc/envs/_build/lib/python3.4/site-packages/databroker-0.3.0-py3.4.egg
number of files: 2
Fixing permissions
Fixing permissions
BUILD END: databroker-0.3.0-py34_0
TEST START: databroker-0.3.0-py34_0
Fetching package metadata: ........
Solving package specifications: ........................................===== testing package: databroker-0.3.0-py34_0 =====
import: 'databroker'
Traceback (most recent call last):
  File "/tmp/edill/ramdisk/mc/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import databroker
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/edill/ramdisk/mc/envs/_test/lib/python3.4/site-packages/databroker-0.3.0-py3.4.egg/databroker/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/edill/ramdisk/mc/envs/_test/lib/python3.4/site-packages/databroker-0.3.0-py3.4.egg/databroker/databroker.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/edill/ramdisk/mc/envs/_test/lib/python3.4/site-packages/metadatastore-0.3.0+6.g7f89195-py3.4.egg/metadatastore/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/edill/ramdisk/mc/envs/_test/lib/python3.4/site-packages/metadatastore-0.3.0+6.g7f89195-py3.4.egg/metadatastore/conf.py", line 74, in <module>
  File "/tmp/edill/ramdisk/mc/envs/_test/lib/python3.4/site-packages/metadatastore-0.3.0+6.g7f89195-py3.4.egg/metadatastore/conf.py", line 70, in load_configuration
KeyError: "The configuration field(s) ['host', 'timezone', 'database', 'port'] were not found in any file or environmental variable."
```

but I am not clear what is triggering that section to have run.

**Comment by ericdill** [comment]
Are you pointing out that the dev configuration is not in the list of packages that immediately follows `The following NEW packages will be INSTALLED:`?

**Comment by ericdill** [comment]
The log is split up in to build and test sections. The build is bracketed by BUILD_START and BUILD_END and the test is bracketed by TEST_START and TEST_END. Also worth noting is that the test section is out of order. The traceback (likely on stderr) was captures before the rest of the output that temporally preceded it but was processed later (on stdout, I would imagine).

**Comment by ericdill** [comment]
*captured

**Comment by tacaswell** [comment]
Ah, I was confused by the out-of-order printing.

The version of mds I built from `conda_prescriptions/recipes/metadatastore/dev` is _also_ missing the patch.
